language: node_js
dist: trusty

git:
  depth: 1

node_js:
  - "8"

script:
  - cd functions
  - npm install firebase-tools
  - npm install
  - firebase serve --only functions --port=9000
  - curl http://localhost:9000/conao3-helper/us-central1/hello
