language: node_js
dist: trusty

git:
  depth: 1

node_js:
  - "8"

install:
  - cd functions
  - npm install firebase-tools
  - npm install

script:
  - firebase serve --only functions --port=9000 --token=$FIREBASE_TOKEN
  - curl http://localhost:9000/conao3-helper/us-central1/hello
